using NUnit.Framework;
using System;

namespace Vein.Numero.Tests.Helpers
{
    internal class NumeroConverterTestsTestCaseSource
    {
        public static TestCaseData CreateTestCaseData(int number, int numberPrefix = 0, string prefix = "")
        {
            return number switch
            {
                1 => new TestCaseData(numberPrefix+1, $"{prefix}jeden"),
                2 => new TestCaseData(numberPrefix+2, $"{prefix}dwa"),
                3 => new TestCaseData(numberPrefix+3, $"{prefix}trzy"),
                4 => new TestCaseData(numberPrefix+4, $"{prefix}cztery"),
                5 => new TestCaseData(numberPrefix+5, $"{prefix}pięć"),
                6 => new TestCaseData(numberPrefix+6, $"{prefix}sześć"),
                7 => new TestCaseData(numberPrefix+7, $"{prefix}siedem"),
                8 => new TestCaseData(numberPrefix+8, $"{prefix}osiem"),
                9 => new TestCaseData(numberPrefix+9, $"{prefix}dziewięć"),
                10 => new TestCaseData(numberPrefix+10, $"{prefix}dziesięć"),
                11 => new TestCaseData(numberPrefix+11, $"{prefix}{NumeroHelper.Number._11}"),
                12 => new TestCaseData(numberPrefix+12, $"{prefix}{NumeroHelper.Number._12}"),
                13 => new TestCaseData(numberPrefix+13, $"{prefix}{NumeroHelper.Number._13}"),
                14 => new TestCaseData(numberPrefix+14, $"{prefix}{NumeroHelper.Number._14}"),
                15 => new TestCaseData(numberPrefix+15, $"{prefix}{NumeroHelper.Number._15}"),
                16 => new TestCaseData(numberPrefix+16, $"{prefix}{NumeroHelper.Number._16}"),
                17 => new TestCaseData(numberPrefix+17, $"{prefix}{NumeroHelper.Number._17}"),
                18 => new TestCaseData(numberPrefix+18, $"{prefix}{NumeroHelper.Number._18}"),
                19 => new TestCaseData(numberPrefix+19, $"{prefix}{NumeroHelper.Number._19}"),
                20 => new TestCaseData(numberPrefix+20, $"{prefix}{NumeroHelper.Number._20}"),
                21 => new TestCaseData(numberPrefix+21, $"{prefix}{NumeroHelper.Number._21}"),
                22 => new TestCaseData(numberPrefix+22, $"{prefix}{NumeroHelper.Number._22}"),
                23 => new TestCaseData(numberPrefix+23, $"{prefix}{NumeroHelper.Number._23}"),
                24 => new TestCaseData(numberPrefix+24, $"{prefix}{NumeroHelper.Number._24}"),
                25 => new TestCaseData(numberPrefix+25, $"{prefix}{NumeroHelper.Number._25}"),
                26 => new TestCaseData(numberPrefix+26, $"{prefix}{NumeroHelper.Number._26}"),
                27 => new TestCaseData(numberPrefix+27, $"{prefix}{NumeroHelper.Number._27}"),
                28 => new TestCaseData(numberPrefix+28, $"{prefix}{NumeroHelper.Number._28}"),
                29 => new TestCaseData(numberPrefix+29, $"{prefix}{NumeroHelper.Number._29}"),
                30 => new TestCaseData(numberPrefix+30, $"{prefix}{NumeroHelper.Number._30}"),
                31 => new TestCaseData(numberPrefix+31, $"{prefix}{NumeroHelper.Number._31}"),
                32 => new TestCaseData(numberPrefix+32, $"{prefix}{NumeroHelper.Number._32}"),
                33 => new TestCaseData(numberPrefix+33, $"{prefix}{NumeroHelper.Number._33}"),
                34 => new TestCaseData(numberPrefix+34, $"{prefix}{NumeroHelper.Number._34}"),
                35 => new TestCaseData(numberPrefix+35, $"{prefix}{NumeroHelper.Number._35}"),
                36 => new TestCaseData(numberPrefix+36, $"{prefix}{NumeroHelper.Number._36}"),
                37 => new TestCaseData(numberPrefix+37, $"{prefix}{NumeroHelper.Number._37}"),
                38 => new TestCaseData(numberPrefix+38, $"{prefix}{NumeroHelper.Number._38}"),
                39 => new TestCaseData(numberPrefix+39, $"{prefix}{NumeroHelper.Number._39}"),
                40 => new TestCaseData(numberPrefix+40, $"{prefix}{NumeroHelper.Number._40}"),
                41 => new TestCaseData(numberPrefix+41, $"{prefix}{NumeroHelper.Number._41}"),
                42 => new TestCaseData(numberPrefix+42, $"{prefix}{NumeroHelper.Number._42}"),
                43 => new TestCaseData(numberPrefix+43, $"{prefix}{NumeroHelper.Number._43}"),
                44 => new TestCaseData(numberPrefix+44, $"{prefix}{NumeroHelper.Number._44}"),
                45 => new TestCaseData(numberPrefix+45, $"{prefix}{NumeroHelper.Number._45}"),
                46 => new TestCaseData(numberPrefix+46, $"{prefix}{NumeroHelper.Number._46}"),
                47 => new TestCaseData(numberPrefix+47, $"{prefix}{NumeroHelper.Number._47}"),
                48 => new TestCaseData(numberPrefix+48, $"{prefix}{NumeroHelper.Number._48}"),
                49 => new TestCaseData(numberPrefix+49, $"{prefix}{NumeroHelper.Number._49}"),
                50 => new TestCaseData(numberPrefix+50, $"{prefix}{NumeroHelper.Number._50}"),
                51 => new TestCaseData(numberPrefix+51, $"{prefix}{NumeroHelper.Number._51}"),
                52 => new TestCaseData(numberPrefix+52, $"{prefix}{NumeroHelper.Number._52}"),
                53 => new TestCaseData(numberPrefix+53, $"{prefix}{NumeroHelper.Number._53}"),
                54 => new TestCaseData(numberPrefix+54, $"{prefix}{NumeroHelper.Number._54}"),
                55 => new TestCaseData(numberPrefix+55, $"{prefix}{NumeroHelper.Number._55}"),
                56 => new TestCaseData(numberPrefix+56, $"{prefix}{NumeroHelper.Number._56}"),
                57 => new TestCaseData(numberPrefix+57, $"{prefix}{NumeroHelper.Number._57}"),
                58 => new TestCaseData(numberPrefix+58, $"{prefix}{NumeroHelper.Number._58}"),
                59 => new TestCaseData(numberPrefix+59, $"{prefix}{NumeroHelper.Number._59}"),
                60 => new TestCaseData(numberPrefix+60, $"{prefix}{NumeroHelper.Number._60}"),
                61 => new TestCaseData(numberPrefix+61, $"{prefix}{NumeroHelper.Number._61}"),
                62 => new TestCaseData(numberPrefix+62, $"{prefix}{NumeroHelper.Number._62}"),
                63 => new TestCaseData(numberPrefix+63, $"{prefix}{NumeroHelper.Number._63}"),
                64 => new TestCaseData(numberPrefix+64, $"{prefix}{NumeroHelper.Number._64}"),
                65 => new TestCaseData(numberPrefix+65, $"{prefix}{NumeroHelper.Number._65}"),
                66 => new TestCaseData(numberPrefix+66, $"{prefix}{NumeroHelper.Number._66}"),
                67 => new TestCaseData(numberPrefix+67, $"{prefix}{NumeroHelper.Number._67}"),
                68 => new TestCaseData(numberPrefix+68, $"{prefix}{NumeroHelper.Number._68}"),
                69 => new TestCaseData(numberPrefix+69, $"{prefix}{NumeroHelper.Number._69}"),
                70 => new TestCaseData(numberPrefix+70, $"{prefix}{NumeroHelper.Number._70}"),
                71 => new TestCaseData(numberPrefix+71, $"{prefix}{NumeroHelper.Number._71}"),
                72 => new TestCaseData(numberPrefix+72, $"{prefix}{NumeroHelper.Number._72}"),
                73 => new TestCaseData(numberPrefix+73, $"{prefix}{NumeroHelper.Number._73}"),
                74 => new TestCaseData(numberPrefix+74, $"{prefix}{NumeroHelper.Number._74}"),
                75 => new TestCaseData(numberPrefix+75, $"{prefix}{NumeroHelper.Number._75}"),
                76 => new TestCaseData(numberPrefix+76, $"{prefix}{NumeroHelper.Number._76}"),
                77 => new TestCaseData(numberPrefix+77, $"{prefix}{NumeroHelper.Number._77}"),
                78 => new TestCaseData(numberPrefix+78, $"{prefix}{NumeroHelper.Number._78}"),
                79 => new TestCaseData(numberPrefix+79, $"{prefix}{NumeroHelper.Number._79}"),
                80 => new TestCaseData(numberPrefix+80, $"{prefix}{NumeroHelper.Number._80}"),
                81 => new TestCaseData(numberPrefix+81, $"{prefix}{NumeroHelper.Number._81}"),
                82 => new TestCaseData(numberPrefix+82, $"{prefix}{NumeroHelper.Number._82}"),
                83 => new TestCaseData(numberPrefix+83, $"{prefix}{NumeroHelper.Number._83}"),
                84 => new TestCaseData(numberPrefix+84, $"{prefix}{NumeroHelper.Number._84}"),
                85 => new TestCaseData(numberPrefix+85, $"{prefix}{NumeroHelper.Number._85}"),
                86 => new TestCaseData(numberPrefix+86, $"{prefix}{NumeroHelper.Number._86}"),
                87 => new TestCaseData(numberPrefix+87, $"{prefix}{NumeroHelper.Number._87}"),
                88 => new TestCaseData(numberPrefix+88, $"{prefix}{NumeroHelper.Number._88}"),
                89 => new TestCaseData(numberPrefix+89, $"{prefix}{NumeroHelper.Number._89}"),
                90 => new TestCaseData(numberPrefix+90, $"{prefix}{NumeroHelper.Number._90}"),
                91 => new TestCaseData(numberPrefix+91, $"{prefix}{NumeroHelper.Number._91}"),
                92 => new TestCaseData(numberPrefix+92, $"{prefix}{NumeroHelper.Number._92}"),
                93 => new TestCaseData(numberPrefix+93, $"{prefix}{NumeroHelper.Number._93}"),
                94 => new TestCaseData(numberPrefix+94, $"{prefix}{NumeroHelper.Number._94}"),
                95 => new TestCaseData(numberPrefix+95, $"{prefix}{NumeroHelper.Number._95}"),
                96 => new TestCaseData(numberPrefix+96, $"{prefix}{NumeroHelper.Number._96}"),
                97 => new TestCaseData(numberPrefix+97, $"{prefix}{NumeroHelper.Number._97}"),
                98 => new TestCaseData(numberPrefix+98, $"{prefix}{NumeroHelper.Number._98}"),
                99 => new TestCaseData(numberPrefix+99, $"{prefix}{NumeroHelper.Number._99}"),
                _ => throw new ArgumentOutOfRangeException(number.ToString()),
            };
        }
    }
}
